name: Java CI with Gradle

on:
  push: [branches, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: |
        ./gradlew build
    - name: Upload release build artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: Release
        path: ./app/build/outputs/apk/release/app-release.apk
    - name: Upload debug build artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: Debug
        path: ./app/build/outputs/apk/debug/app-debug.apk