name: Build Android App on Push

on:
  push:
    branches:
      - main
      - fillwithjoy-patch-1

jobs:
  build_android_app:
    runs-on: ubuntu-latest

    steps:
    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.4.0
